"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, BookOpen, ChevronRight, CircleHelp, CreditCard, FileText, History, LayoutDashboard, LogOut, Menu, Settings, ShieldCheck, User, Wallet, X, TrendingUp } from "lucide-react";

export type Pair = {symbol:string; price:number; change:number; bid:number; ask:number};
export const PAIRS: Pair[] = [
  {symbol:"EUR/USD",price:1.0852,change:0.19,bid:1.0850,ask:1.0852},
  {symbol:"GBP/USD",price:1.2724,change:0.16,bid:1.2722,ask:1.2724},
  {symbol:"USD/JPY",price:149.36,change:0.23,bid:149.34,ask:149.36},
  {symbol:"AUD/USD",price:0.6587,change:0.12,bid:0.6585,ask:0.6587},
  {symbol:"USD/CAD",price:1.3678,change:0.18,bid:1.3676,ask:1.3678},
  {symbol:"USD/CHF",price:0.8612,change:-0.07,bid:0.8610,ask:0.8612}
];

type Trade = {id:string;symbol:string;side:"BUY"|"SELL";lots:number;entry:number;open:number;pl:number;time:string;status:"OPEN"|"CLOSED"};
type UserData = {name:string;email:string;balance:number;equity:number;kyc:"Not started"|"Pending"|"Verified";role:"USER"|"ADMIN"};

const defaultUser:UserData={name:"Demo Trader",email:"demo@shuttytrades.local",balance:10000,equity:10000,kyc:"Not started",role:"USER"};

function loadUser():UserData{if(typeof window==="undefined")return defaultUser;try{return {...defaultUser,...JSON.parse(localStorage.getItem("st_user")||"{}")}}catch{return defaultUser}}
function saveUser(u:UserData){localStorage.setItem("st_user",JSON.stringify(u))}
function loadTrades():Trade[]{if(typeof window==="undefined")return [];try{return JSON.parse(localStorage.getItem("st_trades")||"[]")}catch{return []}}
function saveTrades(t:Trade[]){localStorage.setItem("st_trades",JSON.stringify(t))}
function money(n:number){return `$${n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function price(n:number,s:string){return n.toFixed(s.includes("JPY")?2:4)}

export function AppShell({children,title,active}:{children:React.ReactNode;title:string;active:string}){
  const [open,setOpen]=useState(false);
  const links=[["Dashboard","/dashboard",LayoutDashboard],["Trade","/trade",TrendingUp],["Markets","/markets",BarChart3],["Portfolio","/portfolio",Wallet],["History","/history",History],["KYC","/kyc",ShieldCheck],["Wallet","/wallet",CreditCard],["Support","/support",CircleHelp]];
  return <div className="app-shell">
    <header className="app-top"><button className="mobile-menu btn btn-ghost" onClick={()=>setOpen(!open)}>{open?<X size={18}/>:<Menu size={18}/>}</button><Link href="/" className="brand"><span className="brand-mark">↗</span>Shutty<span>Trades</span></Link><div style={{marginLeft:"auto",display:"flex",gap:10,alignItems:"center"}}><span className="pill green">DEMO MODE</span><Link href="/profile" className="btn btn-ghost"><User size={16}/><span className="desktop-only">Profile</span></Link></div></header>
    <div className="app-layout">
      <aside className={"sidebar "+(open?"mobile-open":"")}><div className="sidebar-section">TRADING</div>{links.map(([n,h,I])=><Link onClick={()=>setOpen(false)} className={"side-link "+(active===n?"active":"")} href={h} key={n as string}><I size={16}/><span>{n}</span></Link>)}<div className="sidebar-section">ACCOUNT</div><Link className={"side-link "+(active==="Settings"?"active":"")} href="/settings"><Settings size={16}/>Settings</Link><Link className={"side-link "+(active==="Admin"?"active":"")} href="/admin"><ShieldCheck size={16}/>Admin console</Link><div style={{marginTop:"auto",padding:"18px 13px"}}><div className="wallet-warning">Real-money trading is inactive. All balances are virtual demo funds.</div></div></aside>
      <main className="main"><div className="topbar"><div><h1 className="page-title">{title}</h1><div className="subtle">Practice environment · Virtual funds only</div></div></div>{children}</main>
    </div>
  </div>
}

export function Dashboard(){
  const [u,setU]=useState(defaultUser); const [trades,setTrades]=useState<Trade[]>([]);
  useEffect(()=>{setU(loadUser());setTrades(loadTrades())},[]);
  const open=trades.filter(t=>t.status==="OPEN");
  return <AppShell title="Dashboard" active="Dashboard"><div className="cards"><div className="stat-card"><small>Demo balance</small><h3>{money(u.balance)}</h3><span className="positive">Available virtual funds</span></div><div className="stat-card"><small>Equity</small><h3>{money(u.equity)}</h3><span className="subtle">Balance + open P/L</span></div><div className="stat-card"><small>Open positions</small><h3>{open.length}</h3><span className="subtle">Active demo trades</span></div><div className="stat-card"><small>KYC status</small><h3 style={{fontSize:20}}>{u.kyc}</h3><span className="subtle">Demo verification flow</span></div></div>
  <div className="grid-2"><div className="panel"><div className="topbar"><div><b>Market overview</b><div className="subtle">Major forex pairs</div></div><Link href="/markets" className="text-link">View all <ChevronRight size={14}/></Link></div>{PAIRS.slice(0,5).map(p=><div className="market-row" key={p.symbol}><b>{p.symbol}</b><span className="quote">{price(p.price,p.symbol)}</span><span>{price(p.bid,p.symbol)}</span><span>{price(p.ask,p.symbol)}</span><span className={p.change>=0?"positive":"negative"}>{p.change>=0?"+":""}{p.change}%</span></div>)}</div>
  <div className="panel"><div className="topbar"><div><b>Quick actions</b></div></div><div style={{display:"grid",gap:10}}><Link className="btn btn-primary" href="/trade">Open demo trade <ChevronRight size={16}/></Link><Link className="btn btn-ghost" href="/portfolio">View portfolio <ChevronRight size={16}/></Link><Link className="btn btn-ghost" href="/kyc">Complete profile/KYC <ChevronRight size={16}/></Link></div><div className="notice" style={{marginTop:15}}>No deposits or withdrawals are processed in this build.</div></div></div>
  <div className="panel" style={{marginTop:15}}><div className="topbar"><div><b>Recent trades</b></div><Link href="/history" className="text-link">History <ChevronRight size={14}/></Link></div>{trades.length===0?<div className="empty">No trades yet. Open your first demo position.</div>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Pair</th><th>Side</th><th>Lots</th><th>Entry</th><th>P/L</th><th>Status</th></tr></thead><tbody>{trades.slice(0,6).map(t=><tr key={t.id}><td>{t.symbol}</td><td className={t.side==="BUY"?"positive":"negative"}>{t.side}</td><td>{t.lots.toFixed(2)}</td><td>{price(t.entry,t.symbol)}</td><td className={t.pl>=0?"positive":"negative"}>{money(t.pl)}</td><td><span className={"pill "+(t.status==="OPEN"?"green":"gray")}>{t.status}</span></td></tr>)}</tbody></table></div>}</div></AppShell>
}

export function TradePage(){
 const [u,setU]=useState(defaultUser); const [pair,setPair]=useState(PAIRS[0]); const [side,setSide]=useState<"BUY"|"SELL">("BUY"); const [lots,setLots]=useState("0.10"); const [sl,setSl]=useState("50"); const [tp,setTp]=useState("100"); const [msg,setMsg]=useState("");
 useEffect(()=>setU(loadUser()),[]);
 const submit=()=>{const l=Math.max(.01,Number(lots)||0); const required=l*1000; if(required>u.balance){setMsg("Insufficient demo margin.");return} const t:Trade={id:crypto.randomUUID(),symbol:pair.symbol,side,lots:l,entry:side==="BUY"?pair.ask:pair.bid,open:side==="BUY"?pair.ask:pair.bid,pl:0,time:new Date().toISOString(),status:"OPEN"}; const ts=[...loadTrades(),t];saveTrades(ts);setMsg(`Demo ${side} order opened for ${pair.symbol}.`);};
 return <AppShell title="Trade" active="Trade"><div className="trade-layout"><div className="panel"><div className="topbar"><div><b>{pair.symbol}</b><div className="subtle">Demo market chart</div></div><select value={pair.symbol} onChange={e=>setPair(PAIRS.find(x=>x.symbol===e.target.value)||PAIRS[0])}>{PAIRS.map(p=><option key={p.symbol}>{p.symbol}</option>)}</select></div><div className="chart-big"><div className="chart-label"><b>{price(pair.price,pair.symbol)}</b> <span className="positive">+{pair.change}%</span></div><svg viewBox="0 0 900 430" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity=".20"/><stop offset="100%" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><polyline points="0,330 45,310 90,335 135,260 180,285 225,220 270,245 315,180 360,205 405,150 450,180 495,120 540,150 585,95 630,135 675,80 720,120 765,65 810,95 855,55 900,75" fill="none" stroke="currentColor" strokeWidth="4"/><polygon points="0,330 45,310 90,335 135,260 180,285 225,220 270,245 315,180 360,205 405,150 450,180 495,120 540,150 585,95 630,135 675,80 720,120 765,65 810,95 855,55 900,75 900,430 0,430" fill="url(#g)"/></svg></div></div>
 <div className="panel order-card"><div><b>New demo order</b><div className="subtle">Margin example uses virtual funds.</div></div><div className="order-tabs"><button className={side==="BUY"?"selected-buy":""} onClick={()=>setSide("BUY")}>BUY {price(pair.ask,pair.symbol)}</button><button className={side==="SELL"?"selected-sell":""} onClick={()=>setSide("SELL")}>SELL {price(pair.bid,pair.symbol)}</button></div><div className="field"><label>PAIR</label><select value={pair.symbol} onChange={e=>setPair(PAIRS.find(x=>x.symbol===e.target.value)||PAIRS[0])}>{PAIRS.map(p=><option key={p.symbol}>{p.symbol}</option>)}</select></div><div className="field"><label>POSITION SIZE (LOTS)</label><input value={lots} onChange={e=>setLots(e.target.value)} inputMode="decimal"/></div><div className="field"><label>STOP LOSS (PIPS)</label><input value={sl} onChange={e=>setSl(e.target.value)}/></div><div className="field"><label>TAKE PROFIT (PIPS)</label><input value={tp} onChange={e=>setTp(e.target.value)}/></div><div className="panel" style={{padding:13}}><div className="subtle">Estimated margin</div><b>{money((Number(lots)||0)*1000)}</b></div><button className={"big-action "+(side==="BUY"?"buy":"sell")} onClick={submit}>Open {side} demo trade</button>{msg&&<div className="notice">{msg}</div>}<div className="wallet-warning">Demo only. This action does not place a live forex order and does not move real money.</div></div></div></AppShell>
}

export function MarketsPage(){return <AppShell title="Markets" active="Markets"><div className="panel"><div className="topbar"><div><b>Forex markets</b><div className="subtle">Illustrative demo quotes</div></div><span className="pill green">SIMULATED</span></div>{PAIRS.map(p=><div className="market-row" key={p.symbol}><b>{p.symbol}</b><span className="quote">{price(p.price,p.symbol)}</span><span>Bid {price(p.bid,p.symbol)}</span><span>Ask {price(p.ask,p.symbol)}</span><span className={p.change>=0?"positive":"negative"}>{p.change>=0?"+":""}{p.change}%</span></div>)}</div></AppShell>}

export function PortfolioPage(){const [ts,setTs]=useState<Trade[]>([]);useEffect(()=>setTs(loadTrades()),[]);return <AppShell title="Portfolio" active="Portfolio"><div className="cards"><div className="stat-card"><small>Open positions</small><h3>{ts.filter(t=>t.status==="OPEN").length}</h3></div><div className="stat-card"><small>Realized P/L</small><h3 className="positive">{money(ts.filter(t=>t.status==="CLOSED").reduce((a,b)=>a+b.pl,0))}</h3></div><div className="stat-card"><small>Win count</small><h3>{ts.filter(t=>t.status==="CLOSED"&&t.pl>0).length}</h3></div><div className="stat-card"><small>Risk mode</small><h3 style={{fontSize:20}}>Demo</h3></div></div><div className="panel" style={{marginTop:15}}><b>Open positions</b>{ts.filter(t=>t.status==="OPEN").length===0?<div className="empty">No open positions.</div>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Pair</th><th>Side</th><th>Lots</th><th>Entry</th><th>Unrealized P/L</th></tr></thead><tbody>{ts.filter(t=>t.status==="OPEN").map(t=><tr key={t.id}><td>{t.symbol}</td><td>{t.side}</td><td>{t.lots.toFixed(2)}</td><td>{price(t.entry,t.symbol)}</td><td className={t.pl>=0?"positive":"negative"}>{money(t.pl)}</td></tr>)}</tbody></table></div>}</div></AppShell>}

export function HistoryPage(){const [ts,setTs]=useState<Trade[]>([]);useEffect(()=>setTs(loadTrades()),[]);return <AppShell title="Trade history" active="History"><div className="panel"><div className="topbar"><div><b>Trade history</b><div className="subtle">Your demo order log</div></div></div>{ts.length===0?<div className="empty">Your trade history will appear here.</div>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Time</th><th>Pair</th><th>Side</th><th>Lots</th><th>Entry</th><th>P/L</th><th>Status</th></tr></thead><tbody>{ts.slice().reverse().map(t=><tr key={t.id}><td>{new Date(t.time).toLocaleString()}</td><td>{t.symbol}</td><td className={t.side==="BUY"?"positive":"negative"}>{t.side}</td><td>{t.lots.toFixed(2)}</td><td>{price(t.entry,t.symbol)}</td><td className={t.pl>=0?"positive":"negative"}>{money(t.pl)}</td><td><span className="pill gray">{t.status}</span></td></tr>)}</tbody></table></div>}</div></AppShell>}

export function KycPage(){const [u,setU]=useState(defaultUser);const [msg,setMsg]=useState("");useEffect(()=>setU(loadUser()),[]);const submit=()=>{const n={...u,kyc:"Pending" as const};saveUser(n);setU(n);setMsg("Demo KYC profile submitted. No identity documents are uploaded or verified in this demo.");};return <AppShell title="KYC & profile verification" active="KYC"><div className="grid-2"><div className="panel"><b>Verification status</b><p className="subtle">This is a demo workflow. Do not upload sensitive identity documents to this local demo build.</p><span className={"pill "+(u.kyc==="Verified"?"green":"gray")}>{u.kyc}</span><div className="field" style={{marginTop:18}}><label>FULL NAME</label><input value={u.name} onChange={e=>setU({...u,name:e.target.value})}/></div><div className="field"><label>EMAIL</label><input value={u.email} onChange={e=>setU({...u,email:e.target.value})}/></div><button className="btn btn-primary" style={{marginTop:16}} onClick={submit}>Submit demo KYC profile</button>{msg&&<div className="notice" style={{marginTop:14}}>{msg}</div>}</div><div className="panel"><ShieldCheck size={28} className="positive"/><h3>Why KYC matters</h3><p className="subtle">A production financial platform would need appropriate customer onboarding, identity verification, risk assessment, AML controls and secure handling of personal data before live services are enabled.</p></div></div></AppShell>}

export function WalletPage(){return <AppShell title="Wallet" active="Wallet"><div className="wallet-warning">Deposits and withdrawals are intentionally disabled. This build has no payment gateway, M-Pesa integration, bank connection, custody system or live broker connection.</div><div className="cards" style={{marginTop:15}}><div className="stat-card"><small>Demo wallet</small><h3>$10,000.00</h3><span className="subtle">Virtual starting balance</span></div><div className="stat-card"><small>Deposits</small><h3>$0.00</h3><span className="subtle">Inactive</span></div><div className="stat-card"><small>Withdrawals</small><h3>$0.00</h3><span className="subtle">Inactive</span></div><div className="stat-card"><small>Funding status</small><h3 style={{fontSize:20}}>Disabled</h3></div></div><div className="panel" style={{marginTop:15}}><b>Funding roadmap</b><p className="subtle">Payment integrations should only be connected after the required legal, regulatory, banking/payment, security, KYC/AML and operational requirements have been established.</p></div></AppShell>}

export function ProfilePage(){const [u,setU]=useState(defaultUser);useEffect(()=>setU(loadUser()),[]);const save=()=>{saveUser(u);alert("Profile saved in this demo browser.")};return <AppShell title="Profile" active="Profile"><div className="panel" style={{maxWidth:700}}><User size={28} className="positive"/><h3>Trader profile</h3><div className="field"><label>NAME</label><input value={u.name} onChange={e=>setU({...u,name:e.target.value})}/></div><div className="field"><label>EMAIL</label><input value={u.email} onChange={e=>setU({...u,email:e.target.value})}/></div><button className="btn btn-primary" style={{marginTop:15}} onClick={save}>Save profile</button></div></AppShell>}

export function SettingsPage(){return <AppShell title="Settings" active="Settings"><div className="support-grid"><div className="panel"><Settings size={24} className="positive"/><h3>Trading preferences</h3><p className="subtle">Default chart: candles · Default order size: 0.10 lots · Notifications: enabled</p></div><div className="panel"><ShieldCheck size={24} className="positive"/><h3>Security</h3><p className="subtle">This demo stores practice data in your browser. Do not use it for real credentials or sensitive documents.</p></div></div></AppShell>}

export function AdminPage(){const [users]=useState([{name:"Demo Trader",email:"demo@shuttytrades.local",kyc:"Not started",role:"USER"},{name:"Platform Admin",email:"admin@shuttytrades.local",kyc:"Verified",role:"ADMIN"}]);return <AppShell title="Admin console" active="Admin"><div className="admin-grid"><div className="admin-card"><small className="subtle">Registered demo users</small><h2>{users.length}</h2></div><div className="admin-card"><small className="subtle">Open demo trades</small><h2>{loadTrades().filter(t=>t.status==="OPEN").length}</h2></div><div className="admin-card"><small className="subtle">Real-money status</small><h2 className="positive">OFF</h2></div></div><div className="panel" style={{marginTop:15}}><b>User management</b><div className="table-wrap"><table className="data-table"><thead><tr><th>User</th><th>Email</th><th>KYC</th><th>Role</th></tr></thead><tbody>{users.map(x=><tr key={x.email}><td>{x.name}</td><td>{x.email}</td><td><span className="pill gray">{x.kyc}</span></td><td>{x.role}</td></tr>)}</tbody></table></div></div><div className="panel" style={{marginTop:15}}><b>Admin safety switch</b><p className="subtle">There is deliberately no UI switch to activate real-money services. Live money, payment processing and live execution are not part of this demo package.</p></div></AppShell>}

export function SupportPage(){return <AppShell title="Support" active="Support"><div className="support-grid"><div className="panel"><CircleHelp size={25} className="positive"/><h3>Help centre</h3><p className="subtle">Check the FAQ for common questions about demo trading, accounts and the platform.</p><Link href="/faq" className="text-link">Open FAQ <ChevronRight size={15}/></Link></div><div className="panel"><BookOpen size={25} className="positive"/><h3>Learning centre</h3><p className="subtle">Learn about position sizing, stop-losses, take-profit orders and trading discipline.</p><Link href="/learning" className="text-link">Open learning centre <ChevronRight size={15}/></Link></div><div className="panel"><FileText size={25} className="positive"/><h3>Support request</h3><div className="field"><label>MESSAGE</label><textarea rows={5} placeholder="Describe your question..."/></div><button className="btn btn-primary" style={{marginTop:12}} onClick={()=>alert("Demo request captured locally.")}>Send demo request</button></div><div className="panel"><b>Platform status</b><p className="subtle">Demo environment operational.</p><span className="pill green">ONLINE</span></div></div></AppShell>}

export function FaqPage(){const items=[["What is ShuttyTrades?","A demo forex trading interface designed for practice and product development."],["Is this real forex trading?","No. The current package uses virtual funds and simulated actions only."],["Can I deposit money?","No. Deposits and withdrawals are intentionally disabled."],["Can I use it on my phone?","Yes. The interface is responsive and designed for mobile, tablet and desktop."],["Does the demo guarantee profits?","No. Trading involves risk, and this demo does not represent real market execution or returns."]];return <AppShell title="FAQ" active="Support"><div className="panel">{items.map(([q,a])=><div className="faq-item" key={q}><h3>{q}</h3><p>{a}</p></div>)}</div></AppShell>}

export function LearningPage(){return <AppShell title="Learning centre" active="Support"><div className="support-grid">{[["Position sizing","Learn how trade size affects margin and potential gains/losses."],["Stop-loss","A risk-control instruction intended to limit loss when price moves against a position."],["Take-profit","An instruction used to close a position at a selected target level."],["Leverage","Leverage can magnify both gains and losses. Understand margin before trading."]].map(x=><div className="panel" key={x[0]}><BookOpen size={22} className="positive"/><h3>{x[0]}</h3><p className="subtle">{x[1]}</p></div>)}</div></AppShell>}

export function Logout(){useEffect(()=>{localStorage.removeItem("st_user");location.href="/login"},[]);return null}
